plugins {
    id 'com.android.application'
}

android {
    namespace 'onl.zvi.blog.app'
    compileSdk 34

    defaultConfig {
        applicationId "onl.zvi.blog.app"
        minSdk 19
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file('keystore/android.keystore')
            storePassword 'zvi123456'
            keyAlias 'zvi'
            keyPassword 'zvi123456'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
